// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbuJ4S8Lqx79jHwx3yEC6lMORkHcgi8Jw',
    appId: '1:122024196750:web:36976623f7d2307c41e7df',
    messagingSenderId: '122024196750',
    projectId: 'ucsi-report',
    authDomain: 'ucsi-report.firebaseapp.com',
    storageBucket: 'ucsi-report.appspot.com',
    measurementId: 'G-CY5XQ86CTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBELlsZq92Fu9RjP4tYS7F8A8rpgN0GjBM',
    appId: '1:122024196750:android:c535b88a59185cd941e7df',
    messagingSenderId: '122024196750',
    projectId: 'ucsi-report',
    storageBucket: 'ucsi-report.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5n1csSQiLEEniC7zmES7wkoT_OgnssU',
    appId: '1:122024196750:ios:2147ba01c586e9ca41e7df',
    messagingSenderId: '122024196750',
    projectId: 'ucsi-report',
    storageBucket: 'ucsi-report.appspot.com',
    iosBundleId: 'com.example.bcpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR5n1csSQiLEEniC7zmES7wkoT_OgnssU',
    appId: '1:122024196750:ios:2147ba01c586e9ca41e7df',
    messagingSenderId: '122024196750',
    projectId: 'ucsi-report',
    storageBucket: 'ucsi-report.appspot.com',
    iosBundleId: 'com.example.bcpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbuJ4S8Lqx79jHwx3yEC6lMORkHcgi8Jw',
    appId: '1:122024196750:web:2a5a8eb8c923643d41e7df',
    messagingSenderId: '122024196750',
    projectId: 'ucsi-report',
    authDomain: 'ucsi-report.firebaseapp.com',
    storageBucket: 'ucsi-report.appspot.com',
    measurementId: 'G-73THJ04BSM',
  );
}
